on:
  push:
    branches:
      - main
#      - release/v3

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    # Do not run on forks
    if: github.repository == 'cpro-js/ui5-vite'
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v4.0.2
        with:
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.CPRO_JS_RELEASE_PLEASE_TOKEN }}

  publish-npm:
    # publish only when released
    if: ${{ needs.release-please.outputs.releases_created == true || needs.release-please.outputs.releases_created == 'true' }}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install packages
        run: yarn --immutable
      - name: Publish packages
        run: yarn workspaces foreach -A --topological-dev --no-private npm publish --tolerate-republish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.CPRO_JS_NPM_TOKEN }}
